// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo-g9ky-E72viCAF8_6qsWQdLwcQ_emVY',
    appId: '1:197554544689:web:3d994c8a6deed620cbb510',
    messagingSenderId: '197554544689',
    projectId: 'magapp-c4f46',
    authDomain: 'magapp-c4f46.firebaseapp.com',
    storageBucket: 'magapp-c4f46.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR6FRLld5usF-JyVhvAvFFQpreWu3tXAU',
    appId: '1:197554544689:android:6750fbdf1600358dcbb510',
    messagingSenderId: '197554544689',
    projectId: 'magapp-c4f46',
    storageBucket: 'magapp-c4f46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRHiz-qp6rtoeqJUpkMYLLcNCTUE5NdWg',
    appId: '1:197554544689:ios:745267b655091a2ecbb510',
    messagingSenderId: '197554544689',
    projectId: 'magapp-c4f46',
    storageBucket: 'magapp-c4f46.firebasestorage.app',
    iosBundleId: 'com.example.omniHelp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRHiz-qp6rtoeqJUpkMYLLcNCTUE5NdWg',
    appId: '1:197554544689:ios:745267b655091a2ecbb510',
    messagingSenderId: '197554544689',
    projectId: 'magapp-c4f46',
    storageBucket: 'magapp-c4f46.firebasestorage.app',
    iosBundleId: 'com.example.omniHelp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo-g9ky-E72viCAF8_6qsWQdLwcQ_emVY',
    appId: '1:197554544689:web:06de22d8c95466eecbb510',
    messagingSenderId: '197554544689',
    projectId: 'magapp-c4f46',
    authDomain: 'magapp-c4f46.firebaseapp.com',
    storageBucket: 'magapp-c4f46.firebasestorage.app',
  );
}
